#!/bin/bash

#$ -P bf528
#$ -cwd
#$ -pe omp 16
#
source /etc/bashrc

module load gcc/8.3.0 star/2.6.0c

GENOMEDIR=/project/bf528/project_3/reference/rn4_STAR

#SRR1177966
STAR --genomeDir $GENOMEDIR --runThreadN 16 --readFilesCommand zcat \
--readFilesIn  /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177966_1.fastq.gz /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177966_2.fastq.gz \
--outSAMtype BAM SortedByCoordinate \
--outFileNamePrefix "/projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/STAR_output/STAR_SRR1177966/"

#SRR1177969
STAR --genomeDir $GENOMEDIR --runThreadN 16 --readFilesCommand zcat \
--readFilesIn  /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177969_1.fastq.gz /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177969_2.fastq.gz \
--outSAMtype BAM SortedByCoordinate \
--outFileNamePrefix "/projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/STAR_output/STAR_SRR1177969/"

#SRR1177970
STAR --genomeDir $GENOMEDIR --runThreadN 16 --readFilesCommand zcat \
--readFilesIn  /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177970_1.fastq.gz /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177970_2.fastq.gz \
--outSAMtype BAM SortedByCoordinate \
--outFileNamePrefix "/projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/STAR_output/STAR_SRR1177970/"

#SRR1177993
STAR --genomeDir $GENOMEDIR --runThreadN 16 --readFilesCommand zcat \
--readFilesIn  /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177993_1.fastq.gz /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177993_2.fastq.gz \
--outSAMtype BAM SortedByCoordinate \
--outFileNamePrefix "/projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/STAR_output/STAR_SRR1177993/"

#SRR1177994
STAR --genomeDir $GENOMEDIR --runThreadN 16 --readFilesCommand zcat \
--readFilesIn  /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177994_1.fastq.gz /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177994_2.fastq.gz \
--outSAMtype BAM SortedByCoordinate \
--outFileNamePrefix "/projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/STAR_output/STAR_SRR1177994/"

#SRR1177995
STAR --genomeDir $GENOMEDIR --runThreadN 16 --readFilesCommand zcat \
--readFilesIn  /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177995_1.fastq.gz /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177995_2.fastq.gz \
--outSAMtype BAM SortedByCoordinate \
--outFileNamePrefix "/projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/STAR_output/STAR_SRR1177995/"

#SRR1177998
STAR --genomeDir $GENOMEDIR --runThreadN 16 --readFilesCommand zcat \
--readFilesIn  /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177998_1.fastq.gz /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1177998_2.fastq.gz \
--outSAMtype BAM SortedByCoordinate \
--outFileNamePrefix "/projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/STAR_output/STAR_SRR1177998/"

#SRR1178001
STAR --genomeDir $GENOMEDIR --runThreadN 16 --readFilesCommand zcat \
--readFilesIn  /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1178001_1.fastq.gz /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1178001_2.fastq.gz \
--outSAMtype BAM SortedByCoordinate \
--outFileNamePrefix "/projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/STAR_output/STAR_SRR1178001/"

#SRR1178003
STAR --genomeDir $GENOMEDIR --runThreadN 16 --readFilesCommand zcat \
--readFilesIn  /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1178003_1.fastq.gz /projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/fastq/SRR1178003_2.fastq.gz \
--outSAMtype BAM SortedByCoordinate \
--outFileNamePrefix "/projectnb/bf528/students/jy357/project-3-im-not-dead-yet/datacurator/STAR_output/STAR_SRR1178003/"
